### ISSUE TITLE
Unsure how to compile on Linux

### ISSUE THREAD

**Issue by avereyishere** [HackerN64/F3DEX3#1]
There Is No Armips Package For Linux, Should I Use armips From SM64 Decomps?

**Comment by sauraen** [comment]
I have developed F3DEX3 exclusively on Linux, so of course it can be compiled on Linux. armips is available here and can be easily built from source. https://github.com/Kingcom/armips#22-building-from-source

**Comment by avereyishere** [comment]
Thanks!
