### ISSUE TITLE
Is this Compatible for vanilla SM64 Decomp?

### ISSUE THREAD

**Issue by ThePlayerRolo** [HackerN64/F3DEX3#19]
You see, I want to use the Hacker64 SM64 decomp fork, but I don't know if there is a MIPS GCC Cross Compiler for mac. So I am asking if this avaible for vanilla  SM64 decomp, and how you would add it.

**Comment by coco875** [comment]
[hackersm64 ](https://github.com/HackerN64/HackerSM64) have it and can provide better support to mod sm64

**Comment by ThePlayerRolo** [comment]
Well I can't use hackersm64 bc I can't find a MIPS GCC Cross Compiler for mac so thats why I'm asking

**Comment by coco875** [comment]
you can compile the mips gcc toolchain of libdragon from source or use the docker container

**Comment by coco875** [comment]
you can have more detail here https://github.com/DragonMinded/libdragon/wiki/Installing-libdragon

**Comment by sauraen** [comment]
You'll need some way to compile N64 code even if you're using vanilla decomp. Most N64 tools these days assume Linux, which most people use via WSL. Things often can theoretically support Mac but that may not be well-tested.

Anyway, F3DEX3 has documentation https://hackern64.github.io/F3DEX3/porting.html for how to port a romhack codebase to it. It is possible to do this for any decompiled game which used a F3D family microcode, including vanilla SM64. But the work has already been done for HackerSM64.

**Comment by ThePlayerRolo** [comment]
good news! I'm on windows now and have set up WSL!
